# Settings that the LAMMPS build will import when this package library is used
# See the README file for more explanation

python_SYSINC = $(shell which python-config > /dev/null 2>&1 && python-config --includes || :)
python_SYSLIB = $(shell which python-config > /dev/null 2>&1 && python-config --ldflags || :)
#python_SYSLIB = -lpython2.7 -lnsl -ldl -lreadline -ltermcap -lpthread -lutil -lm
python_SYSPATH = #-L/global/software/anaconda/anaconda-2.7-5.1.0/lib/python2.7/site-packages
PYTHON=python #2.7
